# Generated by Django 4.2.2 on 2023-08-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='created_by',
        ),
    ]
