# Generated by Django 4.2.2 on 2023-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
