# Generated by Django 4.2.2 on 2023-09-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='total_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='text',
            name='total_replys',
            field=models.IntegerField(default=0),
        ),
    ]
